version: '3'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"

  mobile: 
    build: ./client/mobile
    volumes:
      - shared_cli_volume:/shared_data

  web:
    build: ./client/web
    ports:
      - "8081:3000"
    volumes:
      - shared_cli_volume:/shared_data
    depends_on:
      - server
      - mobile

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=toor
    ports:
      - "8082:8080"
    command: start-dev
    volumes:
      - keycloak_data:/kl_data

volumes:
  shared_cli_volume: # Named volume for sharing app APK
  keycloak_data:  # Named volume for Keycloak
  # postgres_data:  # Named volume for PostgreSQL