version: '3'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - shared_cli_volume:/shared_data

  mobile: 
    build: ./client/mobile
    ports:
      - "8081:8081"
    volumes:
      - shared_cli_volume:/shared_data

volumes:
  shared_cli_volume: