version: '3'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"

  mobile: 
    build: ./client/mobile
    volumes:
      - shared_cli_volume:/shared_data
    
  web:
    build: ./client/web
    ports:
      - "3000:3000"
    volumes:
      - shared_cli_volume:/shared_data

volumes:
  shared_cli_volume: